<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import {onMounted,reactive,ref} from 'vue';import {request} from '../api'
const rows=ref([]),dashboard=ref(null),gates=reactive({}),error=ref('')
const digest='sha256:'+'a'.repeat(64)
const form=reactive({releaseNo:'REL-'+Date.now(),applicationCode:'ORDER-SERVICE',commitSha:'0123456789abcdef0123456789abcdef01234567',artifactDigest:digest,environment:'PRODUCTION',testPassRate:99,criticalVulnerabilities:0,rollbackVersion:'v1.9.0',changeTicket:'CHG-2026-'+String(Date.now()).slice(-6),scheduledAt:new Date().toISOString().slice(0,16),emergencyApproval:false})
async function load(){try{[rows.value,dashboard.value]=await Promise.all([request('/api/devops/releases'),request('/api/devops/releases/dashboard')])}catch(e){error.value=e.message}}
async function create(){try{await request('/api/devops/releases',{method:'POST',body:JSON.stringify(form)});form.releaseNo='REL-'+Date.now();await load()}catch(e){error.value=e.message}}
async function gate(i){try{gates[i.id]=await request(`/api/devops/releases/${i.id}/gate`)}catch(e){error.value=e.message}}
async function act(i,action){if(!confirm('确认执行 '+action+'？'))return;try{if(action==='提交审批')await request(`/api/devops/releases/${i.id}/submit`,{method:'POST'});if(action==='批准发布')await request(`/api/admin/devops/releases/${i.id}/approve?remark=${encodeURIComponent('CAB审批通过')}`,{method:'POST'});if(action==='生产部署')await request(`/api/devops/releases/${i.id}/deploy`,{method:'POST',body:JSON.stringify({artifactDigest:i.artifactDigest,strategy:'CANARY',healthCheckPassed:true})});if(action==='回滚')await request(`/api/devops/releases/${i.id}/rollback`,{method:'POST',body:JSON.stringify({targetVersion:i.rollbackVersion,reason:'运行指标超过阈值'})});await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="head"><div><span>RELEASE CONTROL</span><h3>发布与部署控制台</h3><p>从提交哈希、制品摘要、测试和漏洞门禁，到 CAB 审批、金丝雀部署与受控回滚。</p></div><b>制品不可变</b></section><p v-if="error" class="error" @click="error=''">{{error}} ×</p>
<section v-if="dashboard" class="metrics"><article><span>发布候选</span><b>{{dashboard.total}}</b></article><article><span>待审批</span><b>{{dashboard.pendingApproval}}</b></article><article><span>已部署</span><b>{{dashboard.deployed}}</b></article><article><span>门禁阻断</span><b>{{dashboard.blocked}}</b></article></section>
<form class="card form" @submit.prevent="create"><label>发布单<input v-model="form.releaseNo" required></label><label>应用编码<input v-model="form.applicationCode" required></label><label>Commit SHA<input v-model="form.commitSha" required></label><label>环境<select v-model="form.environment"><option>STAGING</option><option>PRODUCTION</option></select></label><label class="wide">制品摘要<input v-model="form.artifactDigest" required></label><label>变更单号<input v-model="form.changeTicket" required></label><label>计划发布时间<input v-model="form.scheduledAt" type="datetime-local" required></label><label class="check"><input v-model="form.emergencyApproval" type="checkbox">紧急放行</label><label>测试通过率<input v-model.number="form.testPassRate" type="number" min="0" max="100"></label><label>严重漏洞<input v-model.number="form.criticalVulnerabilities" type="number" min="0"></label><label>回滚版本<input v-model="form.rollbackVersion" required></label><button>创建发布候选</button></form>
<section class="card table"><table><thead><tr><th>发布</th><th>变更控制</th><th>代码与制品</th><th>质量</th><th>状态</th><th>门禁</th><th>操作</th></tr></thead><tbody><tr v-for="i in rows"><td><b>{{i.releaseNo}}</b><small>{{i.applicationCode}} · {{i.environment}}</small></td><td>{{i.changeTicket}}<small>{{i.scheduledAt}} · {{i.emergencyApproval?'紧急':'常规'}}</small></td><td><code>{{i.commitSha.slice(0,8)}}</code><small>{{i.artifactDigest.slice(0,20)}}…</small></td><td>{{i.testPassRate}}%<small>严重漏洞 {{i.criticalVulnerabilities}}</small></td><td>{{i.state}}</td><td><button class="text" @click="gate(i)">检查</button><small v-if="gates[i.id]" :class="{blocked:gates[i.id].decision==='BLOCKED'}">{{gates[i.id].decision}} / {{gates[i.id].score}}</small></td><td><button v-if="i.state==='DRAFT'" class="text" @click="act(i,'提交审批')">提交</button><button v-if="i.state==='PENDING_APPROVAL'" class="text" @click="act(i,'批准发布')">批准</button><button v-if="i.state==='APPROVED'" class="text" @click="act(i,'生产部署')">部署</button><button v-if="i.state==='DEPLOYED'" class="text danger" @click="act(i,'回滚')">回滚</button></td></tr></tbody></table></section></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:end;background:#fff;border:1px solid #dce2df;padding:24px 28px;margin-bottom:16px}.head span{font-size:11px;letter-spacing:.16em;color:#b47c2f}.head h3{font-size:24px;margin:5px 0}.head p{margin:0;color:#68777c}.head>b{color:#235a74}.metrics{margin-bottom:16px}.card{background:#fff;border:1px solid #dce2df;padding:20px;margin-bottom:16px}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.form label{display:grid;gap:5px;font-size:12px;color:#68777c}.form input,.form select{border:1px solid #ccd6d2;padding:9px}.form .wide{grid-column:span 2}.check{display:flex!important;align-items:center;gap:8px}.check input{width:17px}.form button{border:0;background:#235a74;color:#fff;font-weight:700}.table{padding:0;overflow:auto}.table table{min-width:1050px}td small{display:block;color:#68777c}.text{border:0;background:transparent;color:#235a74;padding:4px}.danger,.blocked,.error{color:#a03f38}@media(max-width:900px){.form{grid-template-columns:1fr}.form .wide{grid-column:auto}}</style>
